Repository prathmeshranaut/Group_A_TaxFilingSoftware, pull requests merged in 2020-12, with the labels that each got.

#58 Bug fixing with final code pre-release
  src/dependent_details.c
  src/headers/dependent_details.h
  src/headers/new_taxfile.h
  src/headers/spouse_details.h
  src/headers/t2202.h
  src/main.c
  src/spouse_details.c
  src/t2202.c
  src/tax_summary.c
Labels: bug

#63 Added Corresponding Data Files for the Test Functions
  test/data/entry_status_1.txt
  test/data/maritial_status_1.txt
  test/data/world_income_1.txt
Labels: test

#62 Added Test Files for entry_status, world_income and maritial_status
  test/src/entry_status.c
  test/src/maritial_status.c
  test/src/world_income.c
Labels: test

#68 Adding date validation
  data/guide_basic.dat
  data/guide_child.dat
  data/guide_hst.dat
  data/guide_otb.dat
  doc/Tax_filing_software-Page-final.jpg
  src/calculate_tax.c
  src/commons.c
  src/create_new_taxfile.c
  src/dependent_details.c
  src/display_guide.c
  src/entry_status.c
  src/headers/commons.h
  src/headers/dependent_details.h
  src/headers/maritial_status.h
  src/headers/new_taxfile.h
  src/headers/spouse_details.h
  src/headers/t2202.h
  src/input_mailing_address.c
  src/input_new_TaxFile.c
  src/main.c
  src/maritial_status.c
  src/primary_address.c
  src/spouse_details.c
  src/t2202.c
  src/t4.c
  src/tax_summary.c
  src/world_income.c
  test/data/basic_details_1.txt
  test/src/basic_details.c
  test/src/headers/runner.h
Labels: bug

#69 Adding tests
  data/guide_basic.dat
  data/guide_child.dat
  data/guide_hst.dat
  data/guide_otb.dat
  src/calcualte_otbenefits.c
  src/calculate_gst_hst_benefits.c
  src/calculate_tax.c
  src/dependent_details.c
  src/headers/dependent_details.h
  src/headers/gst_hst.h
  src/headers/maritial_status.h
  src/headers/spouse_details.h
  src/main.c
  src/maritial_status.c
  src/spouse_details.c
  src/t2202.c
  src/t4.c
  test/data/maritial_status_1.txt
  test/data/t4_1.txt
  test/data/t4_2.txt
  test/src/headers/runner.h
  test/src/maritial_status.c
  test/src/runner.c
Labels: bug

#72 Updated input OTB to add validations
  src/ot_benefits.c
Labels: enhancement

#73 Ragu r1
  Doxyfile
  data/guide_basic.dat
  data/guide_child.dat
  data/guide_hst.dat
  data/guide_otb.dat
  doc/a.txt
  docs/html/dynsections.js
  docs/html/index.html
  docs/html/menudata.js
  docs/html/search/searchdata.js
  docs/latex/make.bat
  docs/latex/refman.tex
  docs/xml/combine.xslt
  docs/xml/compound.xsd
  docs/xml/index.xml
  docs/xml/index.xsd
  docs/xml/xml.xsd
  src/calcualte_otbenefits.c
  src/calculate_gst_hst_benefits.c
  src/calculate_tax.c
  src/commons.c
  src/create_new_taxfile.c
  src/dependent_details.c
  src/display_guide.c
  src/generate_pdf.c
  src/headers/calculate_tax.h
  src/headers/dependent_details.h
  src/headers/generate_pdf.h
  src/headers/ot_benefits.h
  src/input_mailing_address.c
  src/input_new_TaxFile.c
  src/main.c
  src/ot_benefits.c
  src/tax_summary.c
  test/data/dependent_1.txt
  test/data/spouse_1.txt
  test/data/t2202_1.txt
  test/src/dependent_details.c
  test/src/headers/runner.h
  test/src/runner.c
  test/src/spouse_details.c
  test/src/t2202.c
Labels: bug, documentation, enhancement
